# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_plus_in_primary_fur_color works", {
  expect_true(inherits(check_plus_in_primary_fur_color, "function"))
  
  expect_equal(object = check_plus_in_primary_fur_color(primary_fur_color = c("Grey", "Cinnamon")),
               expected = c(TRUE, TRUE))
  
  expect_equal(object = check_plus_in_primary_fur_color(primary_fur_color = c("Grey", "Cinnamon+Grey")),
               expected = c(TRUE, FALSE))
})

test_that("check_plus_in_primary_fur_color returns errors", {
expect_error(object = check_plus_in_primary_fur_color(primary_fur_color = 52), 
             regexp = "primary_fur_color must be a character")
})

