# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_df_nrows works", {

  toto <- structure(list(mpg = c(21, 21), cyl = c(6, 6)), row.names = c("Mazda RX4", "Mazda RX4 Wag"
), class = "data.frame")
  
  expect_message(
    object = get_df_nrows(df = toto),
    regexp = "The dataset is composed of 2 observations"
  )
  
  
  expect_message(
    object = get_df_nrows(df = iris),
    regexp = "The dataset is composed of 150 observations"
  )
  
  expect_message(
    object = get_df_nrows(df = mtcars),
    regexp = "The dataset is composed of 32 observations"
  )
})

