# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_plus_in_primary_fur_color works", {
  expect_true(inherits(check_plus_in_primary_fur_color, "function")) 
  
  expect_equal(object = check_plus_in_primary_fur_color(primary_fur_color = c("Black", "Black+Cinnamon", "Cinnamon", NA)),
               expected = c(TRUE, FALSE, TRUE, NA))
  
})

test_that("check_plus_in_primary_fur_color produces error", {
  expect_error(object = check_plus_in_primary_fur_color(primary_fur_color = c(5, 6)),
               regexp = "primary_fur_color should be a character")
})
