# WARNING - Generated by {fusen} from dev/flat_check_data.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("check_coordinates works", {
  expect_true(inherits(check_coordinates, "function"))
  
  both_valid_latitude <- c(40.766, 40.799)
  both_valid_longitude <- c(-73.96, -73.95)
  
  
  expect_equal(
    object = check_coordinates(latitude = both_valid_latitude, longitude = both_valid_longitude),
    expected = c(TRUE, TRUE)
  )
  
  both_invalid_latitude <- c(30, 32)
both_invalid_longitude <- c(-100, -99)
  
  expect_equal(
    object = check_coordinates(latitude = both_invalid_latitude, longitude = both_invalid_longitude),
    expected = c(FALSE, FALSE)
  )

  
one_invalid_latitude <- c(40.766, 50)
one_invalid_longitude <- c(-73.95, -100)

  expect_equal(
    object = check_coordinates(latitude = one_invalid_latitude, longitude = one_invalid_longitude),
    expected = c(TRUE, FALSE)
  )
  

})

test_that("check_coordinates returns errors", {
  
  expect_error(object = check_coordinates(latitude = "toto", longitude = "tata"), 
               regexp = "latitude and longitude should be numeric")
  
})
