# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("get_df_nrows works with mtcars", {
    expect_message(
    object = get_df_nrows(df = mtcars),
    regexp = "The dataset is composed of 32 observations"
  )
})


test_that("get_df_nrows works with iris", {
    expect_message(
    object = get_df_nrows(df = iris),
    regexp = "The dataset is composed of 150 observations"
  )
})

test_that("get_df_nrows returns nrows", {

expect_equal(object = get_df_nrows(df = iris), expected = 150)  
expect_equal(object = get_df_nrows(df = mtcars), expected = 32)  
  
})
