# WARNING - Generated by {fusen} from dev/flat_get_info.Rmd: do not edit by hand # nolint: line_length_linter.

#' get_df_nrows
#' 
#' Get a message with a number of rows in a data frame of interest
#' 
#' @param df Dataframe 
#' @importFrom glue glue
#' 
#' @return the number of rows + a message in the console
#' 
#' @export
#' @examples
#' get_df_nrows(df = iris)
#' get_df_nrows(df = mtcars)
get_df_nrows <- function(df){
    
  nrow_df <- nrow(df)

  message(glue("The dataset is composed of {nrow_df} observations"))
  
  return(nrow_df)
}
